### ISSUE TITLE
Documentation should be added

### ISSUE THREAD

**Issue by minhducsun2002** [42tm/iniparser#2]
As the title.
A documentation of usable methods should be presented, instead of requiring the user to browse through the source code each time of usage.

EDIT:
It seems there is no method for extracting data from `ini` files.

**Comment by dungwinux** [comment]
The library is still in development, so there's no document, but we will do it as soon as we can.
At the time of this comment (74713b29ebb), to extract data from `ini` files, you need to call class `iniFile` with your `ini` file's path as parameter. You can look at _test/01.cpp_ for more details.

**Comment by minhducsun2002** [comment]
Does the test file imply that in order to extract data from `ini` files and process on-the-fly, writing to an intermediary file (and read it again) is necessary?
